package com.example.daggerandroid

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.example.daggerandroid.di.CarComponent
import com.example.daggerandroid.di.DaggerCarComponent

class MainActivity : AppCompatActivity() {

    //Late initialise the CarComponent and the Car class
    lateinit var carComponent: CarComponent
    lateinit var car: Car

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // Create an instance of the CarComponent using DaggerCarComponent(generated by Dagger)
        carComponent = DaggerCarComponent.create()

        // Grab an instance of Car from CarComponent
        car = carComponent.getCar()

        //Call the function driveCar()
        car.driveCar()
    }
}